### ISSUE TITLE
Decide package name

### ISSUE THREAD

**Issue by dbarneche** [ropenscilabs/ozrepro#3]
- [ ] Figure out package name
- [ ] Change the name of this remote repo
- [ ] change it in DESCRIPTION

**Comment by smbache** [comment]
* grit
* gitbit
* gitbut

**Comment by timchurches** [comment]
In discussion over dinner last night with Saras and Diego, we wondered about how to position or market this project. In many respects, this is "trainer wheels for git" - they will help you learn to ride the bicycle, and (mostly) stop you from falling off, but ultimately you will want to discard the trainer wheels and ride your git-bike unfettered. That's not to disparage the project - the whole point is to dramatically simplify git use for neophytes and occasional users. But we were wondering if it would be a good idea if the project didn't take itself too seriously, and thus adopted a more frivolous name (and associated marketing material, such as logos, mascots etc).

One candidate for such a frivolous name could even be "trainer wheels for git", abbreviated to "twg", or "git trainer wheels" as "gtw". However, "trainer wheels", while an accurate description, nonetheless carries some pejorative baggage - the project is intended to be useful, and not just a child's toy.

So we thought about something like "ponyfish", after [Ponyfish Island](http://www.ponyfish.com.au), the bar where Saras had birthday drinks prior to dinner. It turns out that the name ponyfish is a reference to a scene from the Wes Anderson film _The Life Aquatic with Steve Zissou_](https://en.wikipedia.org/wiki/The_Life_Aquatic_with_Steve_Zissou), in particular a reference to the exotic crayon ponyfish, as shown in this YouTube clip:

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/Q5U9KpUWIo4/0.jpg)](http://www.youtube.com/watch?v=Q5U9KpUWIo4)

"Crayon Ponyfish" could be abbreviated to just "cpf". Or just "ponyfish", or just "pf".

Some suitable artwork could be purchased (at modest cost!) from an artist on [DeviantArt](https://www.deviantart.com/tag/ponyfish) or similar.

Thoughts?

**Comment by smbache** [comment]
First thought is that I’m bummed that I didn’t make the bar and dinner!!

Second thought is that I like the idea of signaling a “not too serious” identity of the package. Maybe the pony fish reference is a bit too hard to figure out?

**Comment by smbache** [comment]
How about `pog`: **p**iece **o**f **g**it. And almost sounds like pug..

**Comment by dfalster** [comment]
Good ideas. Or go straight to **pug** standing for "pick up git"

**Comment by smbache** [comment]
Except then you don’t get to say “what a forking piece of git” ;-)

**Comment by goldingn** [comment]
Hmmm, do we want to reference git?

We've done a good job of hiding all the confusing git terminology in the API, and the README explicitly states it uses git but is otherwise unrelated, so I think it would be confusing to mention git in the name.

I think it should be obviously about version control (or related topics) to make it easy to remember.

These are all available on CRAN, bioConductor and github (checked with `available::available()`), though a bit long and vague: **record**, **chronicle**, **almanac**, **history**, **changes**, **tardis**

**Comment by dvukcevic** [comment]
Thanks for suggesting further possible names.  My vote is to either stick with **stow** or to change to **history**.

I think **stow** is a good short name that seems unique but also quite evocative of its purpose.

The name **history** is probably more familiar to more people and very accurate about what we do, esp. the notion of a single timeline of changes.  It also makes us sound like a more serious package, IMO, rather than just a 'garage project'.

**Comment by timchurches** [comment]
**history** is good, but what about **changes**? Are any of you old enough to remember David Bowie? ;-)

https://www.youtube.com/watch?v=BPPSu0vaNWA

**Comment by dvukcevic** [comment]
I personally prefer **history** because it sounds more authoritative, but I agree that **changes** has much the same merit as **history**.

Bowie?  I was a kid at the time, so this is how I remember him:
https://www.youtube.com/watch?v=ViftZTfRSt8

**Comment by goldingn** [comment]
@timchurches I definitely had Bowie in mind! It's a shame the single cover for changes wouldn't make as nice a hex sticker as some of the others

**Comment by goldingn** [comment]
I like both **history** and **changes**, though I'm now leaning slightly towards **changes** because `history()` is already a function/R thing. Also because Bowie.

![](https://jobjams.files.wordpress.com/2015/09/changes.jpg?w=1024)

**Comment by smbache** [comment]
How about `snap`

**Comment by goldingn** [comment]
Oh that is nice. I don't think it clearly relates to version control, but I'm not sure it matters all that much if it's as snappy as that.

**Comment by goldingn** [comment]
I suggest we move to a vote.

Please vote for your favourite name by clicking on the reaction button:
<img width="225" alt="screen shot 2017-11-01 at 4 36 19 pm" src="https://user-images.githubusercontent.com/4450731/32261473-dba7e44a-bf22-11e7-95cb-5e23819a731e.png">

and selecting one of the following reactions to cast your vote for a package name:

:+1: - `stow`
😄 - `history`
🎉 - `changes`
:heart: - `snap`

**Comment by goldingn** [comment]
@anikobtoth @smwindecker @dbarneche @smbache @softloud would you like to vote?

**Comment by smbache** [comment]
done

**Comment by goldingn** [comment]
OK, with two votes left to cast, and three vote margin, I'm calling it for `changes` 🎉 🎉 🎉

**Comment by dvukcevic** [comment]
Great work, team.  That's one of the bigger tasks now complete!

**Comment by timchurches** [comment]
@dvukcevic 
> Great work, team. That's one of the bigger tasks now complete!

Next task is the logo, then the sticker design. Then the elevator pitch, and the t-shirts. Followed by  social media. And the launch event. And of course the Xmas party. At some stage, some more code might also need to be written...

**Comment by anikobtoth** [comment]
I'll make a logo! :D hehe

**Comment by timchurches** [comment]
```
library(magick)
stopifnot(packageVersion('magick') >= 1.5)

db_urls <- c("https://goo.gl/HJSHhj", "https://goo.gl/8mSfdA",
             "https://goo.gl/4iLUSW", "https://goo.gl/59Hv2Z",
             "https://goo.gl/Q7BmCH", "https://goo.gl/8ve63V")

db_list = sapply(db_urls, image_read)
dbs <- c(db_list[[1]], db_list[[2]], db_list[[3]], db_list[[4]], 
         db_list[[5]], db_list[[6]], image_charcoal(db_list[[6]]))
(ch_ch_ch_changes <- dbs %>% image_scale(300) %>% image_morph(frames=25) %>% image_animate(dispose="previous"))
image_write(ch_ch_ch_changes, "ch_ch_ch_changes.gif")
```


![ch_ch_ch_changes](https://user-images.githubusercontent.com/2859105/32636750-39e478f0-c60a-11e7-8eda-0da8347d8468.gif)
